### ISSUE TITLE
Remove message in status bar

### ISSUE THREAD

**Issue by PixelT** [mishkinf/vscode-edits-history#1]
It's possible to remove message in status bar when go to prev / next edit?
The message `Prev Edit` or `Next edit` is shown for fraction of second there...

**Comment by mishkinf** [comment]
More than happy to add a settings flag that can control if it is or isn't show in the status bar. Would that solve your use case?

**Comment by PixelT** [comment]
Yeah, could be as an option, because right now when I'm going to prev / next edit, my status bar are blinking, which is a little bit annoying ;)

**Comment by mishkinf** [comment]
@PixelT published a new version 0.1.4 with your request.
