### ISSUE TITLE
CMD+K or CTRL+K breaks VSCode default behavior

### ISSUE THREAD

**Issue by kenijo** [mishkinf/vscode-edits-history#3]
Hi,

I love this extension, it's been a missing feature for a long time and the latest version (VSCode 1.28) only addresses "move to previous edit".

There is an issue however. The default behavior of VSCode is to use CMD+K or CTRL+K as a trigger for a second keyboard shortcut.
By setting CMD+K or CTRL+K to "move to next edit" all the default shortcuts that rely on on a double keyboard shortcut are broken.

**Comment by mishkinf** [comment]
Good call. I have custom keyboard shortcuts. What do you suggest in terms of better default options? Also are you on a mac or a PC?

**Comment by kenijo** [comment]
I am using a PC and I am not quite sure what alternative to use. It looks like extensions for Notepad++, Sublime Text or Atom have been using CTRL+- and CTRL+= to navigation back and forth.
In VSCode those are used to zoom in and out but CTRL+SHIFT+- and CTRL+SHIFT+= are also binded to zoom so it shouldn't be too much of a loss.

**Comment by mishkinf** [comment]
Thank you for the suggestion @kenijo. Will make the default change.
