### ISSUE TITLE
[feature] work with local history

### ISSUE THREAD

**Issue by ctf0** [mishkinf/vscode-edits-history#4]
is it possible to get the extension to work in conjunction with https://github.com/zabel-xyz/local-history ?

so now even file was closed you can still use undo from history files.

ref https://github.com/zabel-xyz/local-history/issues/70

**Comment by mishkinf** [comment]
Thats a great idea. One of the things that is weird about this extension is that it doesn't account for changes to files which may destroy the edits history you have. It's not simple to do without incorporating the idea of what local-history does. Are you free to work on this @ctf0 ? I am open to pull requests. If not, maybe I can get to it sometime.

**Comment by mishkinf** [comment]
Accidentally closed the issue. Reopening

**Comment by ctf0** [comment]
sadly am very new to vscode , so it might take some times to make a prototype.
